### ISSUE TITLE
React update to 15.2.0 - fix errors

### ISSUE THREAD

**Issue by noushka86** [poetic/reacterminator#17]
package.json:44Warning: Unknown prop `indexKey` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by SimpleStack)
    in SimpleStack (created by Stack)
    in Stack (created by App)
    in Provider (created by App)
    in App (created by AppWrapper)
    in AppWrapper (created by MeteorDataContainer)
    in MeteorDataContainerwarning @ package.json:44warnUnknownProperties @ ReactDOMUnknownPropertyDevtool.js:87handleElement @ ReactDOMUnknownPropertyDevtool.js:100onBeforeMountComponent @ ReactDOMUnknownPropertyDevtool.js:105(anonymous function) @ ReactDebugTool.js:27emitEvent @ ReactDebugTool.js:24onBeforeMountComponent @ ReactDebugTool.js:275mountComponent @ ReactReconciler.js:45performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountComponentIntoNode @ shallowEqual.js:104perform @ Transaction.js:138batchedMountComponentIntoNode @ shallowEqual.js:125perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:99_renderNewRootComponent @ shallowEqual.js:294_renderSubtreeIntoContainer @ shallowEqual.js:373render @ shallowEqual.js:394(anonymous function) @ main.jsx:7maybeReady @ startup_client.js:26loadingCompleted @ startup_client.js:38
package.json:44Warning: Unknown DOM property viewbox. Did you mean viewBox?
    in svg (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in Loading (created by App)
    in div (created by SimpleStack)
    in SimpleStack (created by Stack)
    in Stack (created by App)
    in Provider (created by App)
    in App (created by AppWrapper)
    in AppWrapper (created by MeteorDataContainer)
    in MeteorDataContainerwarning @ package.json:44validateProperty @ ReactDOMUnknownPropertyDevtool.js:58warnUnknownProperties @ ReactDOMUnknownPropertyDevtool.js:76handleElement @ ReactDOMUnknownPropertyDevtool.js:100onBeforeMountComponent @ ReactDOMUnknownPropertyDevtool.js:105(anonymous function) @ ReactDebugTool.js:27emitEvent @ ReactDebugTool.js:24onBeforeMountComponent @ ReactDebugTool.js:275mountComponent @ ReactReconciler.js:45mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountComponentIntoNode @ shallowEqual.js:104perform @ Transaction.js:138batchedMountComponentIntoNode @ shallowEqual.js:125perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:99_renderNewRootComponent @ shallowEqual.js:294_renderSubtreeIntoContainer @ shallowEqual.js:373render @ shallowEqual.js:394(anonymous function) @ main.jsx:7maybeReady @ startup_client.js:26loadingCompleted @ startup_client.js:38
package.json:44Warning: Unknown prop `xmlns` on <svg> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in svg (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in Loading (created by App)
    in div (created by SimpleStack)
    in SimpleStack (created by Stack)
    in Stack (created by App)
    in Provider (created by App)
    in App (created by AppWrapper)
    in AppWrapper (created by MeteorDataContainer)
    in MeteorDataContainerwarning @ package.json:44warnUnknownProperties @ ReactDOMUnknownPropertyDevtool.js:87handleElement @ ReactDOMUnknownPropertyDevtool.js:100onBeforeMountComponent @ ReactDOMUnknownPropertyDevtool.js:105(anonymous function) @ ReactDebugTool.js:27emitEvent @ ReactDebugTool.js:24onBeforeMountComponent @ ReactDebugTool.js:275mountComponent @ ReactReconciler.js:45mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountComponentIntoNode @ shallowEqual.js:104perform @ Transaction.js:138batchedMountComponentIntoNode @ shallowEqual.js:125perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:99_renderNewRootComponent @ shallowEqual.js:294_renderSubtreeIntoContainer @ shallowEqual.js:373render @ shallowEqual.js:394(anonymous function) @ main.jsx:7maybeReady @ startup_client.js:26loadingCompleted @ startup_client.js:38
package.json:44Warning: Unknown DOM property stroke-width. Did you mean strokeWidth?
    in circle (created by Loading)
    in svg (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in Loading (created by App)
    in div (created by SimpleStack)
    in SimpleStack (created by Stack)
    in Stack (created by App)
    in Provider (created by App)
    in App (created by AppWrapper)
    in AppWrapper (created by MeteorDataContainer)
    in MeteorDataContainerwarning @ package.json:44validateProperty @ ReactDOMUnknownPropertyDevtool.js:58warnUnknownProperties @ ReactDOMUnknownPropertyDevtool.js:76handleElement @ ReactDOMUnknownPropertyDevtool.js:100onBeforeMountComponent @ ReactDOMUnknownPropertyDevtool.js:105(anonymous function) @ ReactDebugTool.js:27emitEvent @ ReactDebugTool.js:24onBeforeMountComponent @ ReactDebugTool.js:275mountComponent @ ReactReconciler.js:45mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountComponentIntoNode @ shallowEqual.js:104perform @ Transaction.js:138batchedMountComponentIntoNode @ shallowEqual.js:125perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:99_renderNewRootComponent @ shallowEqual.js:294_renderSubtreeIntoContainer @ shallowEqual.js:373render @ shallowEqual.js:394(anonymous function) @ main.jsx:7maybeReady @ startup_client.js:26loadingCompleted @ startup_client.js:38
package.json:44Warning: Unknown DOM property stroke-linecap. Did you mean strokeLinecap?
    in circle (created by Loading)
    in svg (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in div (created by Loading)
    in Loading (created by App)
    in div (created by SimpleStack)
    in SimpleStack (created by Stack)
    in Stack (created by App)
    in Provider (created by App)
    in App (created by AppWrapper)
    in AppWrapper (created by MeteorDataContainer)
    in MeteorDataContainerwarning @ package.json:44validateProperty @ ReactDOMUnknownPropertyDevtool.js:58warnUnknownProperties @ ReactDOMUnknownPropertyDevtool.js:76handleElement @ ReactDOMUnknownPropertyDevtool.js:100onBeforeMountComponent @ ReactDOMUnknownPropertyDevtool.js:105(anonymous function) @ ReactDebugTool.js:27emitEvent @ ReactDebugTool.js:24onBeforeMountComponent @ ReactDebugTool.js:275mountComponent @ ReactReconciler.js:45mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountComponentIntoNode @ shallowEqual.js:104perform @ Transaction.js:138batchedMountComponentIntoNode @ shallowEqual.js:125perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:99_renderNewRootComponent @ shallowEqual.js:294_renderSubtreeIntoContainer @ shallowEqual.js:373render @ shallowEqual.js:394(anonymous function) @ main.jsx:7maybeReady @ startup_client.js:26loadingCompleted @ startup_client.js:38
package.json:44Warning: Unknown prop `params` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in a (created by NavBarEvents)
    in NavBarEvents (created by Connect(NavBarEvents))
    in Connect(NavBarEvents) (created by NavBar)
    in div (created by NavBar)
    in NavBar (created by UserShow)
    in div (created by UserShow)
    in div (created by UserShow)
    in div (created by UserShow)
    in div (created by UserShow)
    in UserShow (created by MeteorDataContainer)
    in MeteorDataContainer (created by App)warning @ package.json:44warnUnknownProperties @ ReactDOMUnknownPropertyDevtool.js:87handleElement @ ReactDOMUnknownPropertyDevtool.js:100onBeforeMountComponent @ ReactDOMUnknownPropertyDevtool.js:105(anonymous function) @ ReactDebugTool.js:27emitEvent @ ReactDebugTool.js:24onBeforeMountComponent @ ReactDebugTool.js:275mountComponent @ ReactReconciler.js:45performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49mountChildren @ ReactMultiChild.js:237_createInitialChildren @ ReactDOMComponent.js:704mountComponent @ ReactDOMComponent.js:529mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49performInitialMount @ ReactCompositeComponent.js:359mountComponent @ ReactCompositeComponent.js:240mountComponent @ ReactReconciler.js:49_mountChildAtIndex @ ReactMultiChild.js:422_updateChildren @ ReactMultiChild.js:338updateChildren @ ReactMultiChild.js:298_updateDOMChildren @ ReactDOMComponent.js:938updateComponent @ ReactDOMComponent.js:767receiveComponent @ ReactDOMComponent.js:723receiveComponent @ ReactReconciler.js:131_updateRenderedComponent @ ReactCompositeComponent.js:729_performComponentUpdate @ ReactCompositeComponent.js:707updateComponent @ ReactCompositeComponent.js:626receiveComponent @ ReactCompositeComponent.js:526receiveComponent @ ReactReconciler.js:131_updateRenderedComponent @ ReactCompositeComponent.js:729_performComponentUpdate @ ReactCompositeComponent.js:707updateComponent @ ReactCompositeComponent.js:626receiveComponent @ ReactCompositeComponent.js:526receiveComponent @ ReactReconciler.js:131_updateRenderedComponent @ ReactCompositeComponent.js:729_performComponentUpdate @ ReactCompositeComponent.js:707updateComponent @ ReactCompositeComponent.js:626receiveComponent @ ReactCompositeComponent.js:526receiveComponent @ ReactReconciler.js:131_updateRenderedComponent @ ReactCompositeComponent.js:729_performComponentUpdate @ ReactCompositeComponent.js:707updateComponent @ ReactCompositeComponent.js:626receiveComponent @ ReactCompositeComponent.js:526receiveComponent @ ReactReconciler.js:131_updateRenderedComponent @ ReactCompositeComponent.js:729_performComponentUpdate @ ReactCompositeComponent.js:707updateComponent @ ReactCompositeComponent.js:626receiveComponent @ ReactCompositeComponent.js:526receiveComponent @ ReactReconciler.js:131_updateRenderedComponent @ ReactCompositeComponent.js:729_performComponentUpdate @ ReactCompositeComponent.js:707updateComponent @ ReactCompositeComponent.js:626performUpdateIfNecessary @ ReactCompositeComponent.js:540performUpdateIfNecessary @ ReactReconciler.js:165runBatchedUpdates @ ReactUpdates.js:152perform @ Transaction.js:138perform @ Transaction.js:138perform @ ReactUpdates.js:91flushBatchedUpdates @ ReactUpdates.js:178closeAll @ Transaction.js:204perform @ Transaction.js:151batchedUpdates @ ReactDefaultBatchingStrategy.js:63enqueueUpdate @ ReactUpdates.js:210enqueueUpdate @ ReactUpdateQueue.js:25enqueueForceUpdate @ ReactUpdateQueue.js:157ReactComponent.forceUpdate @ ReactComponent.js:85(anonymous function) @ ReactMeteorData.jsx:105Tracker.Computation._compute @ tracker.js:323Tracker.Computation._recompute @ tracker.js:342Tracker._runFlush @ tracker.js:507onGlobalMessage @ setimmediate.js:102
user-show?id=W5RSSW3F5C8WMLGLM:1 Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.
package.json:44 Warning: Unknown DOM property maxlength. Did you mean maxLength?
    in input (created by UserEditProfessional)
    in div (created by UserEditProfessional)
    in div (created by UserEditProfessional)
    in form (created by UserEditProfessional)
    in div (created by UserEditProfessional)
    in div (created by UserEditProfessional)
    in div (created by UserEditProfessional)
    in UserEditProfessional (created by Connect(UserEditProfessional))
    in Connect(UserEditProfessional) (created by MeteorDataContainer)
    in MeteorDataContainer (created by App)

**Comment by Chun-Yang** [comment]
Fixed
